# docker-compose.yml
version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/microServiceDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=microServiceDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
